### ISSUE TITLE
gib a live url :"(

### ISSUE THREAD

**Issue by jagrit007** [dracarys18/Portfolio#1]
Give a live URL, too lazy to try it out :"(((

**Comment by dracarys18** [comment]
Soon after finishing the blog section

**Comment by jagrit007** [comment]
Yes, then me steal yo portfolio🥰
Please label the issue urgent

**Comment by ritik-gupta** [comment]
haha yes, waiting

**Comment by jagrit007** [comment]
Live dede jon

**Comment by dracarys18** [comment]
> Live dede jon

https://karthihegde.herokuapp.com/
